version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
    nodejs: "18"
    rust: "1.64"
    golang: "1.19"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
