train:
  seq_length: 10
  batch_size: 100
  epochs: 20
  total_steps: 1000

  checkpoint_interval: 100000
  eval_interval: 16

  pipeline: "PromptPipeline"
  orchestrator: "OfflineOrchestrator"
  trainer: "AccelerateILQLTrainer"

  seed: 1000

model:
  model_path: "CarperAI/randomwalks"
  tokenizer_path: "CarperAI/randomwalks"
  num_layers_unfrozen: -1

optimizer:
  name: "adamw"
  kwargs:
    lr: 2.0e-4
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 1000 # train.total_steps
    eta_min: 2.0e-4

method:
  name: "ilqlconfig"
  tau: 0.8
  gamma: 0.99
  cql_scale: 0.1
  awac_scale: 1
  alpha: 0.1
  steps_for_target_q_sync: 5
  two_qs: true
  gen_kwargs:
    max_new_tokens: 9
    top_k: 1
    beta: 100
    temperature: 1.0
