train:
  seq_length: 10
  batch_size: 100
  epochs: 20
  total_steps: 1000

  checkpoint_interval: 10000
  eval_interval: 20

  pipeline: "PromptPipeline"
  orchestrator: "PPOOrchestrator"
  trainer: "AcceleratePPOTrainer"

model:
  model_path: "CarperAI/randomwalks"
  tokenizer_path: "CarperAI/randomwalks"
  num_layers_unfrozen: -1

optimizer:
  name: "adamw"
  kwargs:
    lr: 3.0e-4
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 1000 # train.total_steps
    eta_min: 3.0e-4

method:
  name: "ppoconfig"
  num_rollouts: 128
  chunk_size: 128
  ppo_epochs: 4
  init_kl_coef: 0.05
  target: 6
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 1.2
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 1
  gen_kwargs:
    max_new_tokens: 9
    top_k: 0.0
    top_p: 1.0
    do_sample: True
