---
name: 📚 Documentation
description: Report an issue related to https://trlx.readthedocs.io/en/latest/index.html
labels:
- documentation

body:
- type: textarea
  attributes:
    label: 📚 The doc issue
    description: >
      Please provide a clear and concise description of what content in https://trlx.readthedocs.io/en/latest/index.html is an issue.
  validations:
    required: true

- type: textarea
  attributes:
    label: Suggest a potential alternative/fix
    description: >
      Tell us how we could improve the documentation in this regard.

- type: markdown
  attributes:
    value: >
      Thanks for contributing 🐠!
