---
name: 🚀 Feature Request
description: Submit a proposal/request for a new trlX feature
labels:
- feature request

body:
- type: textarea
  attributes:
    label: 🚀 The feature, motivation, and pitch
    description: >
      Please provide a clear and concise description of the feature proposal.
      Outline the motivation for the proposal; is your feature request related to a
      specific problem? E.g., *"I'm working on X and would like Y to be
      possible"*. If this is related to another GitHub issue, please link here
      too.
  validations:
    required: true

- type: textarea
  attributes:
    label: Alternatives
    description: >
      A description of any alternative solutions or features you've considered,
      if any.

- type: textarea
  attributes:
    label: Additional context
    description: >
      Add any other context or screenshots about the feature request.

- type: markdown
  attributes:
    value: >
      Thanks for contributing 🐠!
