# model:
#   model_path: "/admin/home-duyphung/refactor_summarize_rlhf/trlx/examples/summarize_rlhf/gptj-supervised-summarize-checkpoint/checkpoint-1000/"  # Name of hf model to load
#   tokenizer_path: "EleutherAI/gpt-j-6B"  # Name of hf tokenizer to load
#   model_type: "AcceleratePPOModel"  # Name of accelerate model type to load
#   num_layers_unfrozen: 8 #-1 # Number of bottom layers to freeze during training

# train:
#   seq_length: 550  # Size of LM context
#   epochs: 50  # Train for max(epochs, total_steps)
#   total_steps: 100000  # Train for max(epochs, total_steps)
#   batch_size: 4  # batch size

#   weight_decay: 0.01 # weight decay param
#   lr_init: 5.0e-6  # init learning rate
#   lr_target: 5.0e-6  # target final learning rate
#   opt_eps: 1.0e-8 
#   opt_betas: [0.9, 0.999] # adam betas
#   checkpoint_dir: "train_eval_ckpt_10percent"
#   checkpoint_interval: 1000  # checkpoint interval
#   eval_interval: 100  # eval interval

#   pipeline: "PromptPipeline"  # prompt pipeline to load
#   orchestrator: "PPOOrchestrator"  # orchestrator to load

# method:
#   name: 'ppoconfig'  # Name of RL method config
#   num_rollouts: 128 #128 # Number of rollouts to collect per epoch
#   chunk_size: 16  # Number of rollouts to collect in one loop of orchestrator
#   ppo_epochs: 4  # Number of ppo epochs
#   init_kl_coef: 0.1  # init kl coefficient
#   target: 6  # target kl coefficient, set None for fixed kl coef
#   horizon: 10000  # PPO horizon
#   gamma: 1 # PPO discount
#   lam: 0.95  # PPO lambda
#   cliprange: 0.2  # clip range
#   cliprange_value: 0.2  # clip range
#   vf_coef: 0.2  # value term weight
#   scale_reward: False # "ref" # "running" # False | "ref" | "running" estimate against which to scale rewards
#   ref_mean: None #2.875
#   ref_std: None #1.177 # rescale rewards with this deviation
#   cliprange_reward: 10
#   gen_kwargs:
#     max_new_tokens: 50  # LM max sample gen length
#     # top_k: 0.0  # top k
#     # top_k: 50
#     # top_p: 0.95  # top p
#     # do_sample: True  # sample
#     # top_k: 0
#     # top_p: 1.0
  
train:
  seq_length: 550
  epochs: 50
  total_steps: 100000
  batch_size: 4

  checkpoint_interval: 1000
  eval_interval: 200

  pipeline: "PromptPipeline"
  orchestrator: "PPOOrchestrator"
  trainer: "AcceleratePPOTrainer"

model:
  #model_path: "/admin/home-duyphung/refactor_summarize_rlhf/trlx/examples/summarize_rlhf/gptj-supervised-summarize-checkpoint/checkpoint-1000/"   
  model_path: "/admin/home-duyphung/refactor_summarize_rlhf/trlx/examples/summarize_rlhf/gptj-supervised-summarize-checkpoint-2ll/checkpoint-1600"
  tokenizer_path: "EleutherAI/gpt-j-6B"
  num_layers_unfrozen: 8

optimizer:
  name: "adamw"
  kwargs:
    lr: 5.0e-6
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 0.01

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 100000 # train.total_steps
    eta_min: 5.0e-6

method:
  name: "ppoconfig"
  num_rollouts: 128
  chunk_size: 16
  ppo_epochs: 4
  init_kl_coef: 0.1
  target: 6
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 0.2
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 10
  gen_kwargs:
    max_new_tokens: 50
    # top_k: 0.0
    # top_p: 0.7
    # do_sample: True
    # temperature: 0.5
