train:
  seq_length: 512
  epochs: 10000
  total_steps: 8000
  batch_size: 1

  checkpoint_interval: 10000
  eval_interval: 1000

  pipeline: "PromptPipeline"
  trainer: "AcceleratePPOTrainer"
  seed: 2000

model:
  model_path: "Dahoas/gptneox-sft-static"
  num_layers_unfrozen: 2

tokenizer:
  tokenizer_path: "EleutherAI/gpt-neox-20b"
  truncation_side: "left"

optimizer:
  name: "adamw"
  kwargs:
    lr: 1.0e-6
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 1000000
    eta_min: 1.0e-6

method:
  name: "ppoconfig"
  num_rollouts: 16
  chunk_size: 4
  ppo_epochs: 2
  init_kl_coef: 0.05
  target: 6
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 1
  scale_reward: "running"
  ref_mean: null
  ref_std: null
  cliprange_reward: 20
  gen_kwargs:
    max_new_tokens: 96
    top_k: 0
    top_p: 1.0
    do_sample: True
