train:
  seq_length: 1024
  epochs: 100
  total_steps: 10000
  batch_size: 4

  checkpoint_interval: 100000
  eval_interval: 1000

  pipeline: "PromptPipeline"
  trainer: "AccelerateSFTTrainer"
  checkpoint_dir: "checkpoints/sft_hh"

model:
  model_path: "EleutherAI/gpt-j-6B"
  num_layers_unfrozen: -1

tokenizer:
  tokenizer_path: "gpt2"
  truncation_side: "left"

optimizer:
  name: "adamw"
  kwargs:
    lr: 1.0e-6
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 10000000
    eta_min: 1.0e-6

method:
  name: "sftconfig"
  gen_kwargs:
    max_new_tokens: 128
    top_k: 20
    temperature: 1.0
