model:
  model_path: "/fsx/home-duyphung/sandbox/refactor_summarize_rlhf/trlx/examples/summarize_rlhf/gptneo-supervised-summarize-checkpoint/checkpoint-1000"  # Name of hf model to load
  tokenizer_path: "EleutherAI/gpt-j-6B"  # Name of hf tokenizer to load
  model_type: "AcceleratePPOModel"  # Name of accelerate model type to load
  num_layers_unfrozen: 8 #-1 # Number of bottom layers to freeze during training

optimizer:
  name: "adamw"
  kwargs:
    lr: 1.412e-4
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 80000 # train.total_steps
    eta_min: 1.412e-4

train:
  seq_length: 512  # Size of LM context
  epochs: 50  # Train for max(epochs, total_steps)
  total_steps: 100000  # Train for max(epochs, total_steps)
  batch_size: 4  # batch size

  checkpoint_interval: 1900  # checkpoint interval
  eval_interval: 100  # eval interval

  pipeline: "PromptPipeline"  # prompt pipeline to load
  orchestrator: "PPOOrchestrator"  # orchestrator to load


method:
  name: 'ppoconfig'  # Name of RL method config
  num_rollouts: 128 #128 # Number of rollouts to collect per epoch
  chunk_size: 16  # Number of rollouts to collect in one loop of orchestrator
  ppo_epochs: 4  # Number of ppo epochs
  init_kl_coef: 0.1  # init kl coefficient
  target: 6  # target kl coefficient, set None for fixed kl coef
  horizon: 10000  # PPO horizon
  gamma: 1 # PPO discount
  lam: 0.95  # PPO lambda
  cliprange: 0.2  # clip range
  cliprange_value: 0.2  # clip range
  vf_coef: 0.2  # value term weight
  scale_reward: 'running' # "ref" # "running" # False | "ref" | "running" estimate against which to scale rewards
  ref_mean: None #2.875
  ref_std: None #1.177 # rescale rewards with this deviation
  cliprange_reward: 10
  gen_kwargs:
    max_new_tokens: 64  # LM max sample gen length
    # top_k: 0.0  # top k
    # top_k: 50
    # top_p: 0.95  # top p
    # do_sample: True  # sample
    #temperature: 0.1
