model:
  model_path: "google/flan-t5-xl" # "lvwerra/gpt2-imdb" # "flan-t5-sentiment/checkpoint-15000"  #"lvwerra/gpt2-imdb" #"google/flan-t5-base"  # Name of hf model to load
  tokenizer_path: "google/flan-t5-xl" # "lvwerra/gpt2-imdb" # "flan-t5-sentiment/checkpoint-15000"  #"lvwerra/gpt2-imdb" #"google/flan-t5-base"  # Name of hf tokenizer to load
  model_type: "AcceleratePPOModel"  # Name of accelerate model type to load
  num_layers_unfrozen: 2 #-1 # Number of bottom layers to freeze during training

optimizer:
  name: "adamw"
  kwargs:
    lr: 5.e-5
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 80000 # train.total_steps
    eta_min: 5.e-5

train:
  seq_length: 64  # Size of LM context
  epochs: 50  # Train for max(epochs, total_steps)
  total_steps: 100000  # Train for max(epochs, total_steps)
  batch_size: 4  # batch size

  checkpoint_interval: 1900  # checkpoint interval
  eval_interval: 100  # eval interval

  pipeline: "PromptPipeline"  # prompt pipeline to load
  orchestrator: "PPOOrchestrator"  # orchestrator to load


method:
  name: 'ppoconfig'  # Name of RL method config
  num_rollouts: 128 #128 # Number of rollouts to collect per epoch
  chunk_size: 16  # Number of rollouts to collect in one loop of orchestrator
  ppo_epochs: 4  # Number of ppo epochs
  init_kl_coef: 0.05  # init kl coefficient
  target: 6  # target kl coefficient, set None for fixed kl coef
  horizon: 10000  # PPO horizon
  gamma: 1 # PPO discount
  lam: 0.95  # PPO lambda
  cliprange: 0.2  # clip range
  cliprange_value: 0.2  # clip range
  vf_coef: 0.2  # value term weight
  scale_reward: False # "ref" # "running" # False | "ref" | "running" estimate against which to scale rewards
  ref_mean: None #2.875
  ref_std: None #1.177 # rescale rewards with this deviation
  cliprange_reward: 10
  gen_kwargs:
    max_new_tokens: 64  # LM max sample gen length
    do_sample: True  # sample
    # top_k: 0.0  # top k
    # top_k: 50
    # top_p: 0.95  # top p
    # do_sample: True  # sample
    #temperature: 0.1
