train:
  seq_length: 1024
  epochs: 100
  total_steps: 10000
  batch_size: 4

  checkpoint_interval: 10000
  eval_interval: 200

  pipeline: "PromptPipeline"
  orchestrator: "PPOOrchestrator"
  # trainer: "AcceleratePPOTrainer"

model:
  model_path:  "flax-community/t5-base-cnn-dm" #  "lvwerra/gpt2-imdb" #"lvwerra/gpt2-imdb"
  model_type: "AcceleratePPOModel"
  tokenizer_path:  "flax-community/t5-base-cnn-dm" #  "lvwerra/gpt2-imdb" #"google/flan-t5-large" # "lvwerra/gpt2-imdb"
  num_layers_unfrozen: -1

optimizer:
  name: "adamw"
  kwargs:
    lr: 1.0e-5
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 10000 # train.total_steps
    eta_min: 1.0e-5

method:
  name: "ppoconfig"
  num_rollouts: 128
  chunk_size: 8
  ppo_epochs: 4
  init_kl_coef: 0.05
  target: 6
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 1
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 10
  gen_kwargs:
    max_new_tokens: 128
    num_beams: 5
    # top_k: 0
    # top_p: 1.0
    # do_sample: True
    # temperature: 0.5
