model:
  model_path : "EleutherAI/gpt-j-6B"
  model_type : "ILQLModel"
  device : "cuda"
  tokenizer_path: "gpt2"
  num_layers_unfrozen: -1

train:
  n_ctx : 512
  epochs : 100
  total_steps : 80000
  batch_size : 32
  grad_clip : 1.0

  lr_ramp_steps : 100
  lr_decay_steps : 3366
  weight_decay : 1.0e-6
  learning_rate_init : 1.0e-3
  learning_rate_target : 1.0e-3

  log_interval : 25
  checkpoint_interval : 100
  eval_interval : 50

  input_size: 1
  gen_size: 32

  pipeline : "OfflinePipeline"
  orchestrator : "OfflineOrchestrator"

  accelerate : true

method:
  name: "ilqlconfig"
  tau: 0.7
  gamma: 0.99
  cql_scale: 0.1
  awac_scale: 1
  alpha: 1
  steps_for_target_q_sync: 10
  beta: 4
  two_qs: true
