train:
  seq_length: 550
  epochs: 100
  total_steps: 5000
  batch_size: 8

  checkpoint_interval: 100000
  eval_interval: 500

  pipeline: "PromptPipeline"
  trainer: "AccelerateILQLTrainer"
  checkpoint_dir: "ilql_summarize_t5"

model:
  model_path: "pvduy/flant5-xl_openai_tldr_sft"
  num_layers_unfrozen: -1
  model_arch_type: "seq2seq"

tokenizer:
  tokenizer_path: "pvduy/flant5-xl_openai_tldr_sft"
  truncation_side: "left"

optimizer:
  name: "adamw"
  kwargs:
    lr: 1.0e-6
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 5000 # train.total_steps
    eta_min: 1.0e-6

method:
  name: "ilqlconfig"
  tau: 0.6
  gamma: 0.99
  cql_scale: 0.1
  awac_scale: 1
  alpha: 0.0001
  beta: 0
  steps_for_target_q_sync: 1
  two_qs: true
  gen_kwargs:
    max_new_tokens: 50
    top_k: 50
    beta: [1, 2, 3]
    temperature: 1.0
