train:
  seq_length: 550
  epochs: 100
  total_steps: 10000
  batch_size: 8

  checkpoint_interval: 100000
  eval_interval: 500

  pipeline: "PromptPipeline"
  trainer: "AccelerateILQLTrainer"
  checkpoint_dir: "gpt-j-ilql-summarize-duy"
  #  tracker: null

model:
  model_path: "/admin/home-duyphung/software/github/pvd/trlx/examples/summarize_rlhf/flan-t5-qa/checkpoint-3000"
  num_layers_unfrozen: -1
  model_arch_type: "seq2seq"

tokenizer:
  tokenizer_path: "/admin/home-duyphung/software/github/pvd/trlx/examples/summarize_rlhf/flan-t5-qa/checkpoint-3000"
  truncation_side: "left"

optimizer:
  name: "adamw"
  kwargs:
    lr: 1.0e-6
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 100000 # train.total_steps
    eta_min: 1.0e-6

method:
  name: "ilqlconfig"
  tau: 0.6
  gamma: 0.99
  cql_scale: 0.1
  awac_scale: 1
  alpha: 0.0001
  beta: 0
  steps_for_target_q_sync: 1
  two_qs: true
  gen_kwargs:
    max_new_tokens: 50
    top_k: 50
    beta: 1
    temperature: 1.0
