train:
  seq_length: 1024
  batch_size: 32
  epochs: 100
  total_steps: 200
  checkpoint_interval: 200
  eval_interval: 20

  pipeline: "PromptPipeline"
  trainer: "NeMoSFTTrainer"
  trainer_kwargs:
    pretrained_model: "/mnt/nvme/home/guac/models/nemo-megatron-gpt-20B/"
    megatron_cfg: "sft_megatron_20b.yaml"
    # pretrained_model: "/mnt/nvme/home/guac/models/nemo-megatron-gpt-1.3B"
    # megatron_cfg: "sft_megatron_1.3b.yaml"
  seed: 1000

model:
  model_path: "gpt2"  # Unused; model path determined in NeMo config
  num_layers_unfrozen: -1

tokenizer:
  tokenizer_path: "gpt2"
  truncation_side: "right"

optimizer:
  name: "adamw"
  kwargs:
    lr: 5.0e-5
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 2000 # train.total_steps
    eta_min: 1.0e-6

method:
  name: "sftconfig"
  gen_kwargs:
    max_new_tokens: 40
    top_k: 0
    top_p: 1.0
    use_greedy: True
