train:
  seq_length: 48
  epochs: 100
  total_steps: 10000
  batch_size: 16

  checkpoint_interval: 10000
  eval_interval: 100

  pipeline: "PromptPipeline"
  orchestrator: "PPOOrchestrator"
  trainer: "AcceleratePPOTrainer"

model:
  model_path: "bigscience/bloom-petals"
  tokenizer_path: "bigscience/bloom-petals"
  num_layers_unfrozen: 0

optimizer:
  name: "adamw"
  kwargs:
    lr: 1.0e-4
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 80000
    eta_min: 1.412e-4

method:
  name: 'ppoconfig'
  num_rollouts: 64
  chunk_size: 4
  ppo_epochs: 4
  init_kl_coef: 0.05
  target: 6
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 1
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 10
  gen_kwargs:
    max_length: 48
    top_k: 0.0
    top_p: 1.0
    do_sample: True
    temperature: 0.5
