train:
  seq_length: 612
  epochs: 100
  total_steps: 100000
  batch_size: 12

  checkpoint_interval: 10000
  eval_interval: 500

  pipeline: "PromptPipeline"
  orchestrator: "PPOOrchestrator"
  trainer: "AcceleratePPOTrainer"

model:
  model_path:  "google/flan-t5-large"
  model_arch_type: "seq2seq"
  tokenizer_path:  "google/flan-t5-large"
  num_layers_unfrozen: 2

optimizer:
  name: "adamw"
  kwargs:
    lr:  1.0e-5
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 10000
    eta_min: 1.0e-6

method:
  name: "ppoconfig"
  num_rollouts: 512
  chunk_size: 12
  ppo_epochs: 4
  init_kl_coef: 0.05
  target:  6
  horizon: 10000
  gamma: 0.99
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 1.0
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 10
  gen_kwargs:
    max_new_tokens: 100